### ISSUE TITLE
datadog CI failed to create a report when test results contain non-utf8 characters

### ISSUE THREAD

**Issue by gfuller1** [DataDog/datadog-ci#1250] opened 2024-03-20 22:32 UTC
### Bug description

When running synthetics from the datadog ci, if the test results contain a special character (such as an error returned during a browser test step) the ci is unable to create the report. 

### Describe what you expected

the datadog ci to gracefully handle special characters and generate the report

### Steps to reproduce the issue

run the following with a test that contains an error in a browser response with a special character not found in utf8.

datadog-ci synthetics run-tests --files synthetics.json --config config.json --jUnitReport test_results.xml

### Additional context

The issue is y'all need to clean the results [here](https://github.com/DataDog/datadog-ci/blob/bee8ce79912669c0783b7a5415e2150c14a8a51b/src/commands/synthetics/reporters/junit.ts#L291) before trying to convert it to utf8 xml.

### Command

synthetics

**Comment by Drarig29** [comment] 2024-03-25 09:35
Hi @gfuller1!

I tried with some special characters and it works as expected. We can't fix your issue if you don't give:
1. An actual example of the special characters you are talking about.
2. An error, with the message and its stack trace.
3. The version of datadog-ci and your Node.js version.

You can also give us a URL to the batch or browser test result for us to inspect what's going wrong.

**Comment by Drarig29** [comment] 2024-04-29 12:36
Closing as we can't reproduce it.

**Closed by Drarig29** 2024-04-29 12:36 UTC
Labels: bug, synthetics
