### ISSUE TITLE
datadog-ci sourcemaps upload command is failing for sourcemaps which are above 8MB

### ISSUE THREAD

**Issue by synaptiko** [DataDog/datadog-ci#141] opened 2021-01-08 14:36 UTC
**Describe what happened**
We have an old app written in Ember and its resulting sourcemap files are 7.9MB (our app) and 12MB (vendor file). We wanted to upload the sourcemaps and your documentation mentions the limit is 50mb: https://docs.datadoghq.com/real_user_monitoring/guide/upload-javascript-source-maps/?tab=webpackjs

Unfortunately the CLI will fail with:
```
❌ Failed upload sourcemap for [dist/app-XYZ.js.map]: Error [ERR_FR_MAX_BODY_LENGTH_EXCEEDED]: Request body larger than maxBodyLength limit
```

When we debugged the problem we found a place in `node_modules/follow-redirects/index.js` where we can put a line:
```
options.maxBodyLength = Infinity;
```

This helped partially, although now we are having `408` (Request Timeout) errors. Is there anything we can do to have our sourcemaps uploaded to your servers?

**Steps to reproduce the issue:**
1. have a large app and generate sourcemaps for js files
2. use `yarn datadog-ci sourcemaps upload` command to upload them

**Expected behaviour:**
It's possible up to the limit mentioned in the docs.

**Actual behaviour:**
It's failing on client and server side because of the limit and timeout respectively.

**Additional context**
 - OS version: Linux 5.10.5 x86_64
 - Node version: v15.5.1

**Comment by synaptiko** [comment] 2021-01-08 15:27
:thinking: Hmm, is it because docs mentions `50mb` and meaning `Mb` (Megabit)?

![image](https://user-images.githubusercontent.com/1593280/104032310-481e7300-51ce-11eb-83e3-e491a53571a4.png)

So in fact only 6.25MB is supported?

**Comment by lraucy** [comment] 2021-01-08 17:28
Hello @synaptiko ! Thank you for reporting. The limit is 50MB, not 50Mb (I'll check if we should update the doc for clarity).

The initial error you had is due to a regression due to a dependency upgrade, a fix is on its way: https://github.com/DataDog/datadog-ci/pull/142

The second error means the sourcemap could not be uploaded in "reasonable" time. Usually that's due to "bad" network connection on the client side. Where are you running `datadog-ci sourcemaps upload` from? Is the network good enough?

**Comment by synaptiko** [comment] 2021-01-08 19:34
@lraucy Thank you for the very fast fix of the regression.

Regarding the second error, I testing it from my local machine and it's true that it's not on any particularly fast network. I just measured it and the upload speed is 2 Mb/s but the connection is quite stable.

I might try to upload it from our CI, if you think that could help.

**Comment by synaptiko** [comment] 2021-01-08 20:24
@lraucy you were right, on our CI it's working, the speed test utility says:
```
$ /drone/src/node_modules/.bin/fast -u
30 Mbps
550 Mbps
```
so I think this issue can be closed now (although I think a slightly higher limit on the API side wouldn't hurt :-)

**Comment by lraucy** [comment] 2021-01-11 10:27
Glad to know it now works on your CI! The fix https://github.com/DataDog/datadog-ci/pull/142 has been released so it should now work as expected even without manually overriding the config. I'm closing the issue.

I'm surprised it doesn't work on your local machine given the bandwidth you mentioned + the stable connection, we'll queue some work to see if we can reproduce and understand what is going on.

**Closed by lraucy** 2021-01-11 10:27 UTC
Labels: bug
