### ISSUE TITLE
react native ci uploads wrong javascript bundle for hermes

### ISSUE THREAD

**Issue by jimbofoo** [DataDog/datadog-ci#771] opened 2023-02-08 16:22 UTC
### Bug description

When using hermes with ios (default now) it seems the datadog ci upload scripts upload the minified javascript main bundle instead of the hermes bytecode bundle. 

for example:
```
Upload of ./main.jsbundle.map for bundle /<redacted>/Release-iphoneos/main.jsbundle on platform ios with project path /<redacted>/frontend
Uploading sourcemap ./main.jsbundle.map for JS file available at /<redacted>/Release-iphoneos/main.jsbundle
```

The hermesc command compiles the javascript bundle to hermes bytecode to a different path:

`/<redacted>/Release-iphoneos/MyApp.app/main.jsbundle`

### Describe what you expected

upload of hermes bundle to datadog

### Steps to reproduce the issue

integrate datadog react native uploading as described here:

https://docs.datadoghq.com/real_user_monitoring/error_tracking/reactnative/

### Command

react-native

**Comment by louiszawadzki** [comment] 2023-02-09 12:53
Hi @jimbofoo, thanks for reaching out!

The file we actually need for unminification process is the minified bundle, not the binary.
Is there any reason why you would expect us to send the binary?

**Comment by jimbofoo** [comment] 2023-02-09 13:15
thanks:
- The Android scripts seem to upload the binary hermes bundle.
- The JavaScript bundle can become very large. The upload can easily go over 50MB (the limit), bundle+sourcemap.

**Comment by louiszawadzki** [comment] 2023-02-09 15:14
Thanks for pointing this out. 
It turns out the bundle is not used in most cases and it is indeed quite large, so we've added a task to disable its upload by default (while leaving an option to upload it).

We'll also double check the Android script, we should be sending the minified bundle as well.
I'll let you know once this is implemented :)

**Comment by louiszawadzki** [comment] 2023-04-20 14:37
Hi @jimbofoo,
On the last version we don't send the bundle file anymore to reduce the upload size.

I'll close this issue for now, feel free to reopen it if the issue is not fixed for you :)

**Closed by louiszawadzki** 2023-04-20 14:37 UTC
Labels: bug, rum
